[versions]
androidGradlePlugin = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.0"

serialization = "1.9.0" # https://github.com/Kotlin/kotlinx.serialization/releases
datetime = "0.7.1" # https://github.com/Kotlin/kotlinx-datetime/releases
coroutines = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines/releases

ktor = "3.3.3" # https://github.com/ktorio/ktor/releases

core = "1.17.0"
work = "2.11.0" # https://developer.android.com/jetpack/androidx/releases/work

compose-bom = "2025.12.00" # https://developer.android.com/develop/ui/compose/bom/bom-mapping

activity-compose = "1.12.2" # https://developer.android.com/jetpack/androidx/releases/activity
navigation-compose = "2.9.6" # https://developer.android.com/jetpack/androidx/releases/navigation
lifecycle = "2.10.0"  # https://developer.android.com/jetpack/androidx/releases/lifecycle

room = "2.8.4" # https://developer.android.com/jetpack/androidx/releases/room

datastore = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/datastore

jsoup = "1.21.2" # https://github.com/jhy/jsoup/releases
korlibs = "6.0.1"

accompanist = "0.37.0"

junit = "4.13.2"
androidx-junit = "1.2.1"
espresso-core = "3.6.1"

[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room"}
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room"}

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
korlibs-crypto = { module = "com.soywiz:korlibs-crypto", version.ref = "korlibs" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
